erp5_wendelin: BytesIO now require byte
data_file = BytesIO(data)
TypeError: a bytes-like object is required, not 'str'

output change because the input changes