ERP5TypeFunctionalTestCase: set $XORG_LOCK_DIR
By setting XORG_LOCK_DIR, we can isolate processes when running on slapos test
nodes, so that instead of having all test runners used the shared /tmp, which
eventually fail with

    EnvironmentError: All displays locked : [':123', ':124', ':125', ...

errors when too many testnodes are currently running or too many testnodes have
left some stale lock files. Eventhough since fbdb4ec903 (test: Do not check
presence of lockfile in /tmp/ to assume Xvfb is running for this display, 2017-06-07)
things have improved, it happens that the lock files are owned by a different
unix user (because it was left by another testnode), then Xvfb is not able to
remove the stale lock file.