OCR: strip trailing spaces from outputs
With a minor update of ghostscript, we again had weird changes:

AssertionError: 'ERP5 is a free software.\n\x0c' != 'ERP5 is a free software.\n\n \n\x0c'