zope4: ZPublisher.mapply uses `__code__` instead of `func_code` (Zope: 740eb601).
Also, `__code__` has been introduced in Python 2.6 (for forwards compatibility
with Python 3) as an alias to func_code which has been completely removed in
Python 3.

This fixes testFunctionalCore failures:
  [...]
    Module ZPublisher.mapply, line 53, in mapply
      code = f.__code__
  AttributeError: 'DefaultGetter' object has no attribute '__code__'