erp5_simulation_fast_input: Solve Divergences dialog: Display all divergences in a single ListBox page.
This dialog and its JS gadget does not handle multiple pages ListBox (because
gadget_solve_divergence_dialog.js assumes that the view is the last part of the URL)
and this is not actually needed (customer seldom goes over the previous limit
to 20 anyway).

How to reproduce:
  1. Create >20 divergences (20 lines per page used to be displayed).
  2. Go to Solve Divergences dialog:
     => gadget_solve_divergence_dialog.js:
        -> location.pathname == /erp5/purchase_order_module/42/Delivery_solveDivergenceAction.
           -> basedir=/erp5/purchase_order_module/42.
              => /erp5/purchase_order_module/42/Delivery_getSolveDivergenceDialogParameterFormBox XHR'ed: OK.
  3. Go to any other ListBox page:
     => gadget_solve_divergence_dialog.js:
        -> location.pathname == /erp5/purchase_order_module/42.
           -> basedir=/erp5/purchase_order_module.
              => /erp5/purchase_order_module/Delivery_getSolveDivergenceDialogParameterFormBox XHR'ed: NOK:
                 [...]
                   Module script, line 4, in Delivery_getSolveDivergenceDialogParameterFormBox
                     - <PythonScript at /erp5/Delivery_getSolveDivergenceDialogParameterFormBox used for /erp5/purchase_order_module>
                     - Line 4
                     solver_process = context.getSolverValueList()[-1]
                 AttributeError: getSolverValueList