runUnitTest: 6f1c45c6 wrongly assumed that '--erp5_sql_connection_string' is always passed.
This is the case with runUnitTest wrapper created by SlapOS but is not actually required
as manage_addERP5Site has 'test test' as default value.

This fixes:
  File "custom_zodb.py", line 70, in <module>
    sql_db = Products.ZMySQLDA.db.DB(os.environ['erp5_sql_connection_string'])
  File "UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'erp5_sql_connection_string'