product/Formulator/Widget: MultiList filed 's value can be a tuple
when render a MultiList field, like Catalog_viewPropertyList/my_sql_clear_catalog_list, in no editable mode

since the value is a tuple, it raise:

 Module Products.Formulator.Field, line 317, in render_htmlgrid
   - __traceback_info__: key=None value=('z0_drop_accounting_transaction', 'z0_drop_alarm', 'z0_drop_catalog', 'z0_drop_catalog_fulltext', 'z0_drop_category', 'z0_drop_content_translation', 'z0_drop_deleted_catalog', 'z0_drop_delivery', 'z0_drop_email', 'z0_drop_fulltext', 'z0_drop_item', 'z0_drop_measure', 'z0_drop_predicate', 'z0_drop_predicate_category', 'z0_drop_quantity_unit_conversion', 'z0_drop_record', 'z0_drop_roles_and_users', 'z0_drop_stock', 'z0_drop_subject', 'z0_drop_transformation', 'z0_drop_translation', 'z0_drop_user', 'z0_drop_versioning', 'z_create_accounting_transaction', 'z_create_alarm', 'z_create_catalog', 'z_create_catalog_fulltext', 'z_create_category', 'z_create_content_translation', 'z_create_deleted_catalog', 'z_create_delivery', 'z_create_email', 'z_create_fulltext', 'z_create_item', 'z_create_measure', 'z_create_predicate', 'z_create_predicate_category', 'z_create_quantity_unit_conversion', 'z_create_record', 'z_create_roles_and_users', 'z_create_stock', 'z_create_subject', 'z_create_transformation', 'z_create_translation', 'z_create_user', 'z_create_versioning')
    return self.widget.render_htmlgrid(self, widget_key, value, REQUEST, render_prefix=render_prefix)
  Module Products.ERP5Form.ProxyField, line 70, in __call__
    return proxied_method(field, *args, **kw)
  Module Products.Formulator.Widget, line 217, in render_htmlgrid
    field._render_helper(key, value, REQUEST, render_prefix=render_prefix)),)
  Module Products.Formulator.Field, line 210, in _render_helper
   - __traceback_info__: key=field_my_sql_clear_catalog_list value=('z0_drop_accounting_transaction', 'z0_drop_alarm', 'z0_drop_catalog', 'z0_drop_catalog_fulltext', 'z0_drop_category', 'z0_drop_content_translation', 'z0_drop_deleted_catalog', 'z0_drop_delivery', 'z0_drop_email', 'z0_drop_fulltext', 'z0_drop_item', 'z0_drop_measure', 'z0_drop_predicate', 'z0_drop_predicate_category', 'z0_drop_quantity_unit_conversion', 'z0_drop_record', 'z0_drop_roles_and_users', 'z0_drop_stock', 'z0_drop_subject', 'z0_drop_transformation', 'z0_drop_translation', 'z0_drop_user', 'z0_drop_versioning', 'z_create_accounting_transaction', 'z_create_alarm', 'z_create_catalog', 'z_create_catalog_fulltext', 'z_create_category', 'z_create_content_translation', 'z_create_deleted_catalog', 'z_create_delivery', 'z_create_email', 'z_create_fulltext', 'z_create_item', 'z_create_measure', 'z_create_predicate', 'z_create_predicate_category', 'z_create_quantity_unit_conversion', 'z_create_record', 'z_create_roles_and_users', 'z_create_stock', 'z_create_subject', 'z_create_transformation', 'z_create_translation', 'z_create_user', 'z_create_versioning')
    render_prefix=render_prefix, **kw)
  Module Products.ERP5Form.ProxyField, line 70, in __call__
    return proxied_method(field, *args, **kw)
  Module Products.Formulator.Widget, line 1129, in render_view
    self.render_items_view(field, value, REQUEST))
  Module Products.Formulator.Widget, line 1122, in render_items_view
    result.append(d[e])
KeyError: ('z0_drop_accounting_transaction', 'z0_drop_alarm', 'z0_drop_catalog', 'z0_drop_catalog_fulltext', 'z0_drop_category', 'z0_drop_content_translation', 'z0_drop_deleted_catalog', 'z0_drop_delivery', 'z0_drop_email', 'z0_drop_fulltext', 'z0_drop_item', 'z0_drop_measure', 'z0_drop_predicate', 'z0_drop_predicate_category', 'z0_drop_quantity_unit_conversion', 'z0_drop_record', 'z0_drop_roles_and_users', 'z0_drop_stock', 'z0_drop_subject', 'z0_drop_transformation', 'z0_drop_translation', 'z0_drop_user', 'z0_drop_versioning', 'z_create_accounting_transaction', 'z_create_alarm', 'z_create_catalog', 'z_create_catalog_fulltext', 'z_create_category', 'z_create_content_translation', 'z_create_deleted_catalog', 'z_create_delivery', 'z_create_email', 'z_create_fulltext', 'z_create_item', 'z_create_measure', 'z_create_predicate', 'z_create_predicate_category', 'z_create_quantity_unit_conversion', 'z_create_record', 'z_create_roles_and_users', 'z_create_stock', 'z_create_subject', 'z_create_transformation', 'z_create_translation', 'z_create_user', 'z_create_versioning')