wendelin: run wendelin related tests with the site setup by configurator
Usually, we use the configurator to set up a Wendelin instance, so it makes sense to run the tests with such an instance as well.

And also this should fixed the random error when run test:

ProgrammingError
(1146, "Table 'erp5_test_2.accounting_transaction' doesn't exist")
Traceback (innermost last):
  Module Products.ERP5Catalog.CatalogTool, line 1002, in uncatalogObjectList
    m.result = self.unindexObject(*m.args, **m.kw)
  Module Products.ERP5Catalog.CatalogTool, line 1017, in unindexObject
    self.uncatalog_object(path=path, uid=uid, sql_catalog_id=sql_catalog_id)
  Module Products.ZSQLCatalog.ZSQLCatalog, line 870, in uncatalog_object
    catalog.uncatalogObject(uid=uid,path=path)
  Module Products.ZSQLCatalog.SQLCatalog, line 1547, in uncatalogObject
    method(uid = uid)
  Module Products.ERP5Type.patches.DA, line 225, in DA__call__
   - <SQL Method at /erp5_portal_30347777537315e139b1afecf8479bcc/portal_catalog/erp5_mysql_innodb/z0_uncatalog_accounting_transaction>
    result=DB__.query(query, self.max_rows_)
  Module Products.ZMySQLDA.db, line 492, in query
    c = self._query(qs)
  Module Products.ZMySQLDA.db, line 435, in _query
    self.db.query(query)
  Module MySQLdb.connections, line 277, in query
    _mysql.connection.query(self, query)
ProgrammingError: (1146, "Table 'erp5_test_2.accounting_transaction' doesn't exist")