ERP5Type: fix regression in properties.dtml
In commit a17bb91030b849d1367db8b3954b81dc830a3ce0 ("py2/py3:
Make Products code compatible with both python2 and python3"),
2to3 changed `_.has_key(...)` to `... in _` whereas _ is not a dict.

Traceback (innermost last):
 ...
 Module OFS.PropertyManager, line 309, in manage_editProperties
   manage_tabs_message=message)
 Module Shared.DC.Scripts.Bindings, line 322, in __call__
   return self._bindAndExec(args, kw, None)
 Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
   return self._exec(bound_data, args, kw)
 Module App.special_dtml, line 185, in _exec
   try: result = render_blocks(self._v_blocks, ns)
 Module DocumentTemplate.DT_In, line 707, in renderwob
   try: append(render(section, md))
 Module DocumentTemplate.DT_Let, line 76, in render
   else: d[name]=expr(md)
 Module DocumentTemplate.DT_Util, line 210, in eval
  - __traceback_info__: _
   return eval(code, d)
 Module <string>, line 1, in <module>

TypeError: argument of type 'TemplateDict' is not iterable