Localizer: fix wrong replacement list -> ensure_list
This list was to cast the tuple, it can cause an AttributeError("'tuple' object has no attribute 'append'",)
error when this branch is used.

This is really an error code path, so that was unnoticed.