erp5_wendelin: fix coding style test
we have test failed with

FAIL: test_rebuild_business_template (CodingStyleTest.CodingStyleTest erp5_wendelin)
Try to rebuild business template to catch packaging errors and make sur output is stable.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/slapgrid/slappart53/t/efq/soft/a79bbcf9fe86c72ad2abc81c82384b4a/parts/erp5/product/ERP5Type/tests/CodingStyleTestCase.py", line 231, in test_rebuild_business_template
    self.assertEqual(diff_files, [])
AssertionError: Lists differ: ['modified: erp5_wendelin/Skin... != []

First list contains 1 additional elements.
First extra element 0:
'modified: erp5_wendelin/SkinTemplateItem/portal_skins/erp5_wendelin/ERP5Site_createDataAnalysisList.xml'

- ['modified: erp5_wendelin/SkinTemplateItem/portal_skins/erp5_wendelin/ERP5Site_createDataAnalysisList.xml']
+ []

probably because change was commited from py3 instance: https://lab.nexedi.com/nexedi/erp5/-/commit/4544833453fc03ff4bbdecb80ab6528640569830