erp5_test_result: handle cases where duration is None
We get a handful of useless messages in the logs otherwise:

```
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

CC: @jerome