trade/mrp: move Delivery Cell action to erp5_mrp
Delivery Cell portal type is not allowed anywhere in erp5_trade,
only in some delivery lines portal types from erp5_mrp.

Testing the view action with html test from erp5_trade fail, because the
test cannot find a valid container to create delivery cell, as
delivery_movement_causality_interaction_workflow expects that this
delivery cell is created within a delivery, it fails with:

      File "Script (Python)", line 1, in DeliveryMovement_calculate
        state_change['object'].getExplanationValue().Delivery_calculate()
    AttributeError: 'NoneType' object has no attribute 'Delivery_calculate'

Move this action in mrp, because only mrp uses Delivery Cell.