patches/pylint: teach astroid about xmlsec modules
python xmlsec's xmlsec.so contains multiple level module in the same
.so (xmlsec, xmlsec.template etc) and this seem to cause problems to
astroid, trying to lint a module containing:

  import xmlsec
  xmlsec.template.encrypted_data_create('...')

cause an error:

   File "develop-eggs/astroid-1.3.8+slapospatched001-py2.7.egg/astroid/raw_building.py", line 360, in _set_proxied
      return _CONST_PROXY[const.value.__class__]
  KeyError: <type 'module'>

and unlike similar error happening with ffi's module from cryptography,
retrying does not help.