bt5/erp5_wendelin/DataBucketStream: Fix getBucketByIndex
Before this patch 'getBucketByIndex' was buggy & would fail with

    AttributeError: 'str' object has no attribute 'value'

But it wasn't recognized, because this method wasn't tested before. This
patch adds a test to the method & fixes it.