ZODB Components: Backward compatibility with instances before ZODB Interfaces/Mixins (e84d2b5).
e84d2b5 introduced template_{interface,mixin}_id BusinessTemplate properties
in erp5_property_sheets without keeping backward compatibility and thus
preventing update:
  Module Products.ERP5.Tool.TemplateTool, line 1446, in upgradeSite
    update_catalog=update_catalog)
  Module Products.ERP5.Tool.TemplateTool, line 1289, in updateBusinessTemplateFromUrl
    imported_bt5 = self.download(url = download_url, id = id)
  Module Products.ERP5.Tool.TemplateTool, line 382, in download
    bt = self._download_local(path, id)
  Module Products.ERP5.Tool.TemplateTool, line 328, in _download_local
    bt.importFile(path)
  Module Products.ERP5.Document.BusinessTemplate, line 5887, in importFile
    self.storeTemplateItemData()
  Module Products.ERP5.Document.BusinessTemplate, line 5165, in storeTemplateItemData
    InterfaceTemplateItem(self.getTemplateInterfaceIdList())
AttributeError: getTemplateInterfaceIdList