ListBox: Use `mapply` in `ListMethodWrapper`
`ListMethodWrapper` passed Listbox's list arguments to the wrapped
method, which breaks for `objectValues` when it does not accept extra
arguments.
We instead use `mapply`, to pass only the parameters it expects.

This bug was detected by navigating to the Metadata tab of an extension
component (which does not subclass `Folder`, and thus inherits
the `objectValues` method from Zope's `SimpleItem`).
After commit 4441e5c8f9c4d7e350af54752b7f9c48542c19c8, which adds a
listbox to show subobjects in the Metadata tab, this gives an error
such as:

```
Error Type: TypeError
Error Value: Item.objectValues() got an unexpected keyword argument 'checked_permission'
```