officejs_ooffice: fix non existant appcache on web sites
This caused upgrader errors such as:

    Error: Web Site web_site_module/ooffice_spreadsheet references a non existant appcache gadget_officejs_spreadsheet.appcache