officejs: fix non existant appcache on officejs_smart_assistant
This caused upgrader to error with:

    Error: Web Site web_site_module/officejs_smart_assistant references a non existant appcache gadget_officejs_spreadsheet.appcache