ERP5Type.Base: Remove setDescription.
Documents should inherit from XMLObject, which already overloads this
setter. As a result, this method is normally not used.
The problem is that it gets called when calling
  newTempBase(
    description='foo'
  )
which fails with:
  AttributeError: _setDescription
because _setProperty finds setDescription and tries to call it, instead
of setting description as a local property..