web: depend on erp5_crm
"contact us" feature of erp5_web uses erp5_crm

testTemplateTool depend on the actual order of installation of business
template, so update it now that the order has changed.

configurator scripts also had to be updated, so that
erp5_ingestion_mysql_innodb_catalog is installed before erp5_web/erp5_crm
because since erp5_crm depends on ingestion, it will install
erp5_ingestion_mysql_innodb_catalog, which has new tables and SQL methods
for indexation, so it needs to be installed with `update_catalog=True`.

As we can see here, configurator uses installBusinessTemplateListFromRepository
to install business templates one by one (in the same order that they are
added with addConfigurationItem), and pass update_catalog only for
business templates which add new tables/indexation methods and needs a
catalog update after install, but what happened is that we install
erp5_web with update_catalog=False, which will install
erp5_ingestion_mysql_innodb_catalog, also with update_catalog=False so
the activities to install business templates fail with errors like:

    ProgrammingError: (1146, "Table 'erp5_test_*.email' doesn't exist")