erp5_core: fix `TypeError` on raise in `Base_edit`
String value raised with `ValueError` had an extra `%s` at the end, hence
raising another error when formatting:

> TypeError: not enough arguments for format string

This commit simply removes the extra formatting character, since I could not
guess what should have been printed here.