oauth2_resource: fix property id
This object was not exported with its actual ID, reindexing cause
warnings in the log, like this:

    2023-02-13 08:13:47,169 WARNING CMFActivity Message dropped (no object found at path ('', 'erp5', 'portal_property_sheets', 'OAuth2AuthorisationClientConnector', 'usable_as_default_property'))
    Traceback (most recent call last):
      File "./parts/erp5/product/CMFActivity/ActivityTool.py", line 282, in getObject
        obj = self._getObject(activity_tool)
      File "./parts/erp5/product/CMFActivity/ActivityTool.py", line 276, in _getObject
        obj = obj[id]
      File "./eggs/Zope2-2.13.30-py2.7.egg/OFS/ObjectManager.py", line 783, in __getitem__
        raise KeyError, key
    KeyError: 'usable_as_default_property'