mrp: fix getAggregatedAmountList on py3 when some lines do not have int_index
This was causing this kind of errors:

    Module erp5.component.document.erp5_version.TradeCondition, line 127, in getAggregatedAmountList
      return context.getAggregatedAmountList(*args, **kw)
    Module erp5.component.mixin.erp5_version.AmountGeneratorMixin, line 516, in getAggregatedAmountList
      return self.getGeneratedAmountList(*args, **kw).aggregate()
    Module erp5.component.mixin.erp5_version.AmountGeneratorMixin, line 338, in getGeneratedAmountList
      amount_generator_line_list.sort(key=getLineSortKey)
  TypeError: '<' not supported between instances of 'int' and 'NoneType'