ZODB Components: Fix startup of old Sites not having portal_components yet.
In such case, it must obviously be considered that the ZODB Component Document
was not found and thus fallback on filesystem Document.

2018-11-21 17:05:01,919 WARNING ERP5Type.Dynamic Could not access Portal Type Object for type 'Category Tool'
Traceback (most recent call last):
  File "product/ERP5Type/dynamic/lazy_class.py", line 3
52, in loadClass
    class_definition = generatePortalTypeClass(site, portal_type)
  File "product/ERP5Type/dynamic/portal_type_class.py",
 line 198, in generatePortalTypeClass
    module = erp5.component.document.find_load_module(type_class)
  File "product/ERP5Type/dynamic/component_package.py",
 line 361, in find_load_module
    loader = self.find_module(fullname)
  File "product/ERP5Type/dynamic/component_package.py",
 line 155, in find_module
    component_tool = aq_base(site.portal_components)
AttributeError: portal_components