item: fix Item_getTrackingListGraphAsJSON on py3
py3 is more strict:

     >>> json.dumps({"a": 1, 2:"b"})
     '{"a": 1, "2": "b"}'
     >>> json.dumps({"a": 1, 2:"b"}, sort_keys=True)
     Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "(SR)/parts/python3/lib/python3.11/json/__init__.py", line 238, in dumps
       **kw).encode(obj)
             ^^^^^^^^^^^
     File "(SR)/parts/python3/lib/python3.11/json/encoder.py", line 200, in encode
        chunks = self.iterencode(o, _one_shot=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "(SR)/parts/python3/lib/python3.11/json/encoder.py", line 258, in iterencode
       return _iterencode(o, 0)
              ^^^^^^^^^^^^^^^^^
     TypeError: '<' not supported between instances of 'int' and 'str'

fix this by not using int keys in the first place, they get converted
to str so we can do it ourselves