patches/pylint: fix regression with namedtuples
with namedtuples and unicode literals enabled, our patch break with:

  Module py2stdlib, line 266, in infer_named_tuple
    ''' % {'name': name, 'fields': attributes})
  Module Products.ERP5Type.patches.pylint, line 74, in string_build
    encoding = _guess_encoding(data)
  Module astroid.builder, line 65, in _guess_encoding
    if string.startswith('\xef\xbb\xbf'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)