payment_mean: make "limit" required
Submitting the field with an empty limit now cause an error like:

    ValueError: invalid literal for int() with base 10: ''

For simplicity, make the field required.

Also set a small default value and a range, to prevent accidentally displaying
too much when there's lot of data matching.