trade: remove Delivery Cell view action
Delivery Cell portal type is not allowed anywhere in erp5_trade.

Testing the view action with html test from erp5_trade fail, because the
test cannot find a valid container to create delivery cell, as
delivery_movement_causality_interaction_workflow expects that this
delivery cell is created within a delivery, it fails with:

      File "Script (Python)", line 1, in DeliveryMovement_calculate
        state_change['object'].getExplanationValue().Delivery_calculate()
    AttributeError: 'NoneType' object has no attribute 'Delivery_calculate'