erp5_accounting&trade&pdm: Missing set ConstraintType on constraints
   This is expected that constraints can call getConstraintType() if they are filtered:

    return context.checkConsistency(fixit=1, filter={'constraint_type': 'post_upgrade'},)
  Module Products.ERP5Type.Core.Folder, line 1476, in checkConsistency
    error_list.extend(obj.fixConsistency(filter=filter, **kw))
  Module Products.ERP5Type.Base, line 2714, in fixConsistency
    return self.checkConsistency(fixit=True, filter=filter, **kw)
  Module Products.ERP5Type.Core.Folder, line 1476, in checkConsistency
    error_list.extend(obj.fixConsistency(filter=filter, **kw))
  Module Products.ERP5Type.Base, line 2714, in fixConsistency
    return self.checkConsistency(fixit=True, filter=filter, **kw)
  Module Products.ERP5Type.Core.Folder, line 1462, in checkConsistency
    **kw
  Module Products.ERP5Type.Base, line 2686, in checkConsistency
    for constraint_instance in self._filteredConstraintList(filter):
  Module Products.ERP5Type.Base, line 2739, in _filteredConstraintList
    constraints = [x for x in constraints if x.__of__(self).getConstraintType() in \
AttributeError: 'RequestContainer' object has no attribute 'getConstraintType'