testDynamicClassGeneration: check gc.garbage with original value instead of []
when install erp5 and wendelin together, then run this test, it failed with

  File "/srv/slapgrid/slappart15/t/dda/soft/65312bdf4ef69b687424c3250f508beb/parts/erp5/Products/ERP5Type/tests/testDynamicClassGeneration.py", line 2912, in testGC
    self.assertEqual(gc.garbage, [])
AssertionError: Lists differ: [<regex._regex_core.Group obje... != []

gc.garbage contains regex._regex_core.Group object, it's probably introduced by wendelin init which can't be collected

let's test with original garbage value instead of [](??)