Float64 Numpy array test
@Tyagov 
 
Added a test to check int64 and float64 Numpy arrays because an error like this existed before:

```
in Base_executeJupyter
     return json.dumps(result)
   Module json, line 244, in dumps
     return _default_encoder.encode(obj)
   Module json.encoder, line 207, in encode
     chunks = self.iterencode(o, _one_shot=True)
   Module json.encoder, line 270, in iterencode
     return _iterencode(o, 0)
   Module json.encoder, line 184, in default
     raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([[ -245554.,    19410.,  1453313.],
        [ -238947.,    18888.,  1443651.],
        [ -238416.,    18350.,  1444382.],
        ...,
        [ -250816.,    19482.,  1445528.],
        [ -251464.,    18678.,  1444711.],
        [ -253475.,    18786.,  1444842.]]) is not JSON serializable
```

/reviewed-on https://lab.nexedi.com/nexedi/erp5/merge_requests/285