erp5_core: move back ContributionPredicate to file system
This partially reverts 96bbfad246 (ZODB Components: More Documents to migrate
from Products.ERP5.Document., 2020-06-29) because of test failures:

    ======================================================================
    ERROR: test_GET_on_document (testWebDavSupport.TestWebDavSupport)
    Get data from document in webdav
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "Products/ERP5/tests/testWebDavSupport.py", line 214, in test_GET_on_document
        document = document_module[filename]
      File "OFS/ObjectManager.py", line 783, in __getitem__
        raise KeyError, key
    KeyError: 'P-DMS-Presentation.3.Pages-001-en.odp'