Revert "py3: sortKey() must be a string as comparison between str and None/int/tuple now raises TypeError."
This reverts commit 192c2000fa156aad7feecc5253c1c5a3147d2e36.

This commit introduced a test failure with testCommitOrder
testInvalidationBug.TestInvalidationBug [1]

    Traceback (most recent call last):
      File "Products/ERP5/tests/testInvalidationBug.py", line 93, in testCommitOrder
        self.assertEqual(result_list[1], [0,0])  # activity buffer first
    AssertionError: Lists differ: [1, 0] != [0, 0]

    First differing element 0:
    1
    0

    - [1, 0]
    ?  ^

    + [0, 0]
    ?  ^

That commit was apparently in the good direction, because transaction
API specifies that sortKey must return string

https://github.com/zopefoundation/transaction/blob/6cf10102948a8f4e36092a9b402e3859d6db4ccd/CHANGES.rst#141-2013-02-20
https://github.com/zopefoundation/transaction/blob/33448417ab526327757f05e23b1884786c805629/src/transaction/interfaces.py#L524-L534