zope4py3: send() must be bytes(), not str().
  File "product/TimerService/timerserver/TimerServer.py", line 71, in run
    s.send('GET / HTTP/1.1\r\n\r\n')
TypeError: a bytes-like object is required, not 'str'