test_result: tolerate buildout section ids with -
parsing of reference in TestResult_getTestSuiteData did not handle
properly buildout section ids with -, this was causing

  File "Script (Python)", line 30, in TestResult_getTestSuiteData
    buildout_section_id_and_commits_count, revision = repository_string.split('-')
  ValueError: too many values to unpack