officejs_support_request_ui_test: adjust test for Distributed Cache
With distributed cache, removing from cache is only done once the transaction
is committed, so the test needs to commit explictly, as the default behavior
is to abort the transaction in teardown.
Without this, this test was leaking and causing next tests to fail:

    ======================================================================
    FAIL: test_support_request_comment_include_other_event_type (erp5.component.test.erp5_version.testSupportRequest.TestSupportRequestCommentOnExistingSupportRequest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "<portal_components/test.erp5.testSupportRequest>", line 391, in test_support_request_comment_include_other_event_type
        ignoreKeys(json.loads(support_request.SupportRequest_getCommentPostListAsJson()), 'message_id'))
    AssertionError: Lists differ: [{'attachment_name': None, 'da... != [{u'attachment_name': None, u'...

    Second list contains 1 additional elements.
    First extra element 1:
    {u'date': u'2021-06-24T08:56:00+00:00', u'attachment_link': u'document_module/2', u'attachment_name': u'attached_file.txt', u'text': u'<p>look </p>', u'user': u'erp5.component.test.erp5_version.testSupportRequest.TestSupportRequestCommentOnExistingSupportRequest.test_html_escape'}

    Diff is 1320 characters long. Set self.maxDiff to None to see it.