forge: set a title to the commit gadget field
This fixes the testNamingConvention failure:

    AssertionError: erp5_vcs/BusinessTemplate_viewVcsStatusDialog : your_commit_json : can't be empty

Since this field is in bottom group, the label is not rendered, so it's
not needed to hide field name with some TALES.