core: prevent TypeError with debit/credit_price when total_price is NULL
On python3, using debit_price or credit_price on an InventoryListBrain
for a movement where price is None caused an error on python3:

   TypeError: '>' not supported between instances of 'int' and 'NoneType'

On python2, before this change it was returning 0 which was not really
correct, now this is None.