erp5_banking_core: Doesn't actually provide erp5_full_text_catalog.
Moreover, since this was added and because of a bug in bt5 implementation of
provide dependencies, it was not possible to install this bt5 from TemplateTool
on a fresh instance:
  [...]
    File "product/ERP5Type/tests/runUnitTest.py", line 417, in _installBusinessTemplateList
      with_test_dependency_list=True)]
    File "product/ERP5/Tool/TemplateTool.py", line 1200, in resolveBusinessTemplateListDependency
      return self.sortBusinessTemplateList(list(bt5_set))
    File "product/ERP5/Tool/TemplateTool.py", line 947, in sortBusinessTemplateList
      "Circular dependencies on %s" % reverse_dependency_dict.keys()
  NotImplementedError: Circular dependencies on ['erp5_mysql_innodb_catalog', 'erp5_banking_core', 'erp5_property_sheets', 'erp5_core', 'erp5_pdm', 'erp5_trade', 'erp5_accounting', 'erp5_core_proxy_field_legacy', 'erp5_simulation', 'erp5_base']

  -> erp5_banking_core depends on erp5_trade.
  --> erp5_trade depends on erp5_base.
  ---> erp5_base depends on erp5_full_text_catalog meta bt5 resolved to erp5_banking_core (provision_list).

This fixes testBanking* Unit Tests failures since ERP5Banking migration to ZODB
Components (0d2bd4c) not triggered with FS Unit Tests because it does not try to
resolve dependencies and just install them in getBusinessTemplateList() order.