fixup! New portal type: External Method
This fixes commit ea53f23e623043e85ea731faa826a38960055b1c:

  ERROR Application Couldn't install ERP5Type
  Traceback (most recent call last):
    File "OFS/Application.py", line 691, in install_product
      initmethod(context)
    File "Products/ERP5Type/__init__.py", line 141, in initialize
      initializeProductDocumentRegistry()
    File "Products/ERP5Type/InitGenerator.py", line 62, in initializeProductDocumentRegistry
      importLocalDocument(class_id, class_path=class_path)
    File "Products/ERP5Type/Utils.py", line 994, in importLocalDocument
      module = __import__(module_path, {}, {}, (module_path,))
    File "Products/ERP5/Document/ExternalMethod.py", line 38, in <module>
      class ExternalMethod(XMLObject, ZopeExternalMethod, ExpressionMixin):
  TypeError: Error when calling the metaclass bases
      metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

What happened is that the API of ExpressionMixin changed in commit
df85ef46aa72988e03e0d503a8a3b99395553fe5 and the backward compatibility
code (product/ERP5/mixin/expression.py) was broken.

Also fix 'filter' tab on in the catalog.
See also commit 6ad56d89dc4bad7cfdb4502cfaca8f142cf1435d.