CatalogTool: fix upgradeSchema with python scripts
Python scripts can be used as catalog methods, including as "clear catalog"
methods. This was causing error when upgradeSchema was called:

    product/ERP5Catalog/CatalogTool.py", line 1372, in upgradeSchema
      method_list_by_connection_id[method.connection_id].append(method)
    AttributeError: connection_id