ProcessingNodeTestCase: respect isSubscribed state of activity tool
This is needed when running livetests in a runUnitTest instance, in the
following scenario:
 - `runUnitTest --save test_bt:testXXX`
 - `runUnitTest --save --load`
 - run the live test from the browser

because livetest way of processing activities is to unsubscribe at the
beginning of the test and subscribe at the end to have control of
activities when running .tic, if ProcessingNodeTestCase also process the
activities automatically, they interfere and test often fail with errors like:

```
File "ERP5Type/tests/ProcessingNodeTestCase.py", line 249, in tic
  raise RuntimeError(error_message)
RuntimeError: tic is looping forever. These messages are pending: [('/erp5/portal_components/test.erp5.testSupportRequest', 'immediateReindexObject', 1, 0), ('/erp5/support_request_module/2617', 'immediateReindexObject', -1, 0)]
```

/reviewed-on https://lab.nexedi.com/nexedi/erp5/merge_requests/779